spring:
  application:
    name: basic-mq
  datasource:
    platform: postgres
    username: ${DB_USER:basic_mq}
    password: ${DB_PASSWORD:pwd123}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5431}/${DB_NAME:basic_mq}?stringtype=unspecified
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/master.xml
    contexts: ${CHANGE_LOG:dev}
    user: ${DB_USER:basic_mq}
    password: ${DB_PASSWORD:pwd123}
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: ${RABBITMQ_USER:user}
    password: ${RABBITMQ_PASSWORD:bitnami}

server:
  port: ${PORT:9099}